-- Description: Analytical Queries for Job Application Management System

-- 1. Total Applications per Job
SELECT JOB_TITLE,
       COUNT(APP_ID) AS TOTAL_APPLICATIONS
FROM JOB_APPLICATIONS JA
JOIN JOBS J ON JA.JOB_ID = J.JOB_ID
GROUP BY JOB_TITLE
ORDER BY TOTAL_APPLICATIONS DESC;
/

-- 2. Total Applicants per Department
SELECT J.DEPARTMENT,
       COUNT(DISTINCT A.APPLICANT_ID) AS TOTAL_APPLICANTS
FROM JOB_APPLICATIONS JA
JOIN JOBS J ON JA.JOB_ID = J.JOB_ID
JOIN APPLICANTS A ON JA.APPLICANT_ID = A.APPLICANT_ID
GROUP BY J.DEPARTMENT
ORDER BY TOTAL_APPLICANTS DESC;
/

-- 3. Application Status Count per Job
SELECT J.JOB_ID,
       J.JOB_TITLE,
       JA.STATUS,
       COUNT(JA.APP_ID) AS STATUS_COUNT,
       ROUND(COUNT(JA.APP_ID)*100.0/SUM(COUNT(JA.APP_ID)) OVER(PARTITION BY J.JOB_ID),2) AS PERCENTAGE
FROM JOB_APPLICATIONS JA
JOIN JOBS J ON JA.JOB_ID = J.JOB_ID
GROUP BY J.JOB_ID, J.JOB_TITLE, JA.STATUS
ORDER BY J.JOB_ID, JA.STATUS;
/

-- 4. Top 5 Applicants by Number of Jobs Applied
SELECT A.APPLICANT_ID,
       A.FIRST_NAME || ' ' || A.LAST_NAME AS APPLICANT_NAME,
       COUNT(JA.JOB_ID) AS JOBS_APPLIED
FROM JOB_APPLICATIONS JA
JOIN APPLICANTS A ON JA.APPLICANT_ID = A.APPLICANT_ID
GROUP BY A.APPLICANT_ID, A.FIRST_NAME, A.LAST_NAME
ORDER BY JOBS_APPLIED DESC
FETCH FIRST 5 ROWS ONLY;
/

-- 5. Average Salary per Department
SELECT DEPARTMENT,
       AVG(SALARY) AS AVG_SALARY
FROM JOBS
GROUP BY DEPARTMENT
ORDER BY AVG_SALARY DESC;
/

-- 6. Total Applications per Date
SELECT TRUNC(APPLICATI) AS APP_DATE,
       COUNT(APP_ID) AS TOTAL_APPLICATIONS
FROM JOB_APPLICATIONS
GROUP BY TRUNC(APPLICATI)
ORDER BY APP_DATE;
/

-- 7. Approved Applications per Applicant
SELECT A.APPLICANT_ID,
       A.FIRST_NAME || ' ' || A.LAST_NAME AS APPLICANT_NAME,
       COUNT(JA.APP_ID) AS APPROVED_APPLICATIONS
FROM JOB_APPLICATIONS JA
JOIN APPLICANTS A ON JA.APPLICANT_ID = A.APPLICANT_ID
WHERE JA.STATUS = 'APPROVED'
GROUP BY A.APPLICANT_ID, A.FIRST_NAME, A.LAST_NAME
ORDER BY APPROVED_APPLICATIONS DESC;
/

-- 8. Rejected Applications per Job
SELECT J.JOB_ID,
       J.JOB_TITLE,
       COUNT(JA.APP_ID) AS REJECTED_COUNT,
       (SELECT COUNT(*) FROM JOB_APPLICATIONS WHERE JOB_ID = J.JOB_ID) AS TOTAL_APPLICATIONS,
       ROUND(COUNT(JA.APP_ID)*100.0/(SELECT COUNT(*) FROM JOB_APPLICATIONS WHERE JOB_ID = J.JOB_ID),2) AS REJECTED_PERCENT
FROM JOB_APPLICATIONS JA
JOIN JOBS J ON JA.JOB_ID = J.JOB_ID
WHERE JA.STATUS = 'REJECTED'
GROUP BY J.JOB_ID, J.JOB_TITLE
ORDER BY J.JOB_ID;
/

-- 9. Applications per Department per Month
SELECT J.DEPARTMENT,
       TO_CHAR(JA.APPLICATI,'MM-MON-YY') AS MONTH,
       COUNT(JA.APP_ID) AS TOTAL_APPLICATIONS
FROM JOB_APPLICATIONS JA
JOIN JOBS J ON JA.JOB_ID = J.JOB_ID
GROUP BY J.DEPARTMENT, TO_CHAR(JA.APPLICATI,'MM-MON-YY')
ORDER BY J.DEPARTMENT, MONTH;
/

