-- Description: Audit & Monitoring Queries for Job Application Management System
-- Database: mon_27801_valens_jobApplication_db


-- 1. VIEW ALL AUDIT LOG ENTRIES
SELECT *
FROM AUDIT_LOG
ORDER BY LOG_ID DESC;



-- 2. VIEW ONLY FAILED OPERATIONS (DENIED BY TRIGGERS)
SELECT *
FROM AUDIT_LOG
WHERE ACTION_STATUS = 'DENIED'
ORDER BY LOG_ID DESC;



-- 3. VIEW ONLY SUCCESSFUL OPERATIONS
SELECT *
FROM AUDIT_LOG
WHERE ACTION_STATUS = 'ALLOWED'
ORDER BY LOG_ID DESC;



-- 4. CHECK ACTIVITY PER USER
SELECT USERNAME,
       COUNT(*) AS TOTAL_ACTIONS,
       SUM(CASE WHEN ACTION_STATUS = 'DENIED' THEN 1 ELSE 0 END) AS DENIED_COUNT,
       SUM(CASE WHEN ACTION_STATUS = 'ALLOWED' THEN 1 ELSE 0 END) AS ALLOWED_COUNT
FROM AUDIT_LOG
GROUP BY USERNAME
ORDER BY TOTAL_ACTIONS DESC;



-- 5. CHECK ACTIVITY BY OPERATION TYPE (INSERT/UPDATE/DELETE)
SELECT ACTION_TYPE,
       COUNT(*) AS TOTAL_ACTIONS,
       SUM(CASE WHEN ACTION_STATUS = 'DENIED' THEN 1 ELSE 0 END) AS DENIED_COUNT,
       SUM(CASE WHEN ACTION_STATUS = 'ALLOWED' THEN 1 ELSE 0 END) AS ALLOWED_COUNT
FROM AUDIT_LOG
GROUP BY ACTION_TYPE
ORDER BY TOTAL_ACTIONS DESC;



-- 6. CHECK AUDIT LOGS ON PUBLIC HOLIDAYS ONLY
SELECT A.*
FROM AUDIT_LOG A
JOIN PUBLIC_HOLIDAYS H
  ON TRUNC(A.ACTION_DATE) = TRUNC(H.HOLIDAY_DATE)
ORDER BY A.LOG_ID DESC;



-- 7. CHECK WEEKDAY VIOLATIONS (MON–FRI)
SELECT LOG_ID,
       USERNAME,
       ACTION_DATE,
       ACTION_TYPE,
       ACTION_STATUS
FROM AUDIT_LOG
WHERE ACTION_STATUS = 'DENIED'
  AND TO_CHAR(ACTION_DATE, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH') NOT IN ('SAT','SUN')
ORDER BY LOG_ID DESC;



-- 8. CHECK OPERATIONS DURING WEEKENDS
SELECT LOG_ID,
       USERNAME,
       ACTION_DATE,
       ACTION_TYPE,
       ACTION_STATUS
FROM AUDIT_LOG
WHERE TO_CHAR(ACTION_DATE, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH') IN ('SAT','SUN')
ORDER BY LOG_ID DESC;



-- 9. Summary of allowed vs denied actions per day
SELECT TRUNC(ACTION_DATE) AS ACTION_DAY,
       COUNT(*) AS TOTAL_ACTIONS,
       SUM(CASE WHEN ACTION_STATUS = 'DENIED' THEN 1 ELSE 0 END) AS DENIED_COUNT,
       SUM(CASE WHEN ACTION_STATUS = 'ALLOWED' THEN 1 ELSE 0 END) AS ALLOWED_COUNT
FROM AUDIT_LOG
GROUP BY TRUNC(ACTION_DATE)
ORDER BY ACTION_DAY DESC;


-- 10. VIEW HOLIDAY LIST (FOR VERIFICATION)
SELECT *
FROM PUBLIC_HOLIDAYS
ORDER BY HOLIDAY_DATE;
